# Generated by Django 5.0.14 on 2026-02-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_bannedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedip',
            name='banned_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
