# Generated by Django 5.0.14 on 2026-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('event_type', models.CharField(choices=[('SSH_BRUTE_FORCE', 'SSH Brute Force'), ('PORT_SCAN', 'Port Scan'), ('LOGIN_FAILURE', 'Login Failure')], max_length=50)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('attempts', models.IntegerField(default=1)),
                ('blocked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
