# Generated by Django 5.0.14 on 2026-03-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_attackevent_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackevent',
            name='event_type',
            field=models.CharField(choices=[('SSH_BRUTE_FORCE', 'SSH Brute Force'), ('PORT_SCAN', 'Port Scan'), ('LOGIN_FAILURE', 'Login Failure')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attackevent',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
    ]
