# Generated by Django 5.0.14 on 2026-03-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_attackevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attackevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
